### ISSUE TITLE
springfactory.scad generates an error with default settings.

### ISSUE THREAD

**Issue by bassamanator** [jshessen/SpringFactory#1]
```
WARNING: Ignoring unknown module 'threaded_rod' in file springfactory.scad, line 632 
```

**Comment by jshessen** [comment]
@bassamanator 

I have just ran a check against a current iteration of the repo:

`$git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean`



Here is the output from OpenSCAD "Preview"


OpenSCAD 2021.01
https://www.openscad.org/

Copyright (C) 2009-2021 The OpenSCAD Developers
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

Loaded design '/mnt/development/GitHub/SpringFactory/SpringFactory.scad'.
Used file cache size: 5 files
Compiling design (CSG Tree generation)...
ECHO: "--> Make "Bolt" Base"
ECHO: "----> Begin "Bolt" Base Creation"
ECHO: "**======> Base Diameter (D=X/Y): 31.983**"
ECHO: "**======> Base Height (Z): 5.7835**"
ECHO: "**======> Base Cutout Rotation Angle: 13**"
ECHO: "--> Make "Bolt" Grip"
ECHO: "----> Begin "Bolt" Grip Creation"
ECHO: "**======> Grip Width (X): 5.835**"
ECHO: "**======> Grip Length (Y): 59.935**"
ECHO: "**======> Grip Height (Z): 5.7835**"
ECHO: "--> Make "Bolt" Threads"
ECHO: "----> Begin "Bolt" Thread Creation"
ECHO: "**======> Thread Diameter (X/Y): 8**"
ECHO: "**======> Thread Height (Z): 47.5**"
ECHO: "**======> Thread Pitch (P): 2.4**"
ECHO: "--> Make "Bolt" Wire Eyelet"
ECHO: "----> Begin "Bolt" Eyelet Creation"
ECHO: "**======> Eyelet Width (X): 5.835**"
ECHO: "**======> Eyelet Height (Z): 9.88978**"
ECHO: "**======> Eyelet Radius (r): 15.9915**"
ECHO: "**======> Eyelet Extrusion Length: 27**"
ECHO: "**======> Eyelet Z-Rotation Offset Angle: 3**"
ECHO: "--> Make "Bolt" Wire Catch"
ECHO: "----> Begin "Bolt" Catch Creation"
ECHO: "**======> Catch Width (X): 5.835**"
ECHO: "**======> Catch Height (Z): 9.88978**"
ECHO: "**======> Catch Radius (r): 15.9915**"
ECHO: "**======> Catch Extrusion Length: 25.4**"
ECHO: "**======> Catch Z-Rotation Offset Angle: -20.83**"
ECHO: "--> Make "Screw" Base"
ECHO: "----> Begin "Screw" Base Creation"
ECHO: "**======> Base Diameter (D=X/Y): 14.9836**"
ECHO: "**======> Base Height (Z): 7.79505**"
ECHO: "--> Make "Screw" Grip"
ECHO: "----> Begin "Screw" Grip Creation"
ECHO: "**======> Grip Width (X): 5.835**"
ECHO: "**======> Grip Length (Y): 47.8**"
ECHO: "**======> Grip Height (Z): 6.62**"
ECHO: "--> Make "Screw" Threads"
ECHO: "----> Begin "Screw" Thread Creation"
ECHO: "**======> Thread Diameter (X/Y): 8**"
ECHO: "**======> Thread Height (Z): 6.62**"
ECHO: "**======> Thread Pitch (P): 2.4**"
ECHO: "--> Make "Screw" Wire Eyelet"
ECHO: "----> Begin "Screw" Eyelet Creation"
ECHO: "**======> Eyelet Width (X): 5.99605**"
ECHO: "**======> Eyelet Height (Z): 11.9921**"
ECHO: "**======> Eyelet Radius (r): 7.4918**"
ECHO: "**======> Eyelet Extrusion Length: 100**"
ECHO: "**======> Eyelet Z-Rotation Offset Angle: -98**"
ECHO: "--> Make "Cap" Threads"
ECHO: "----> Begin "Cap" Thread Creation"
ECHO: "**======> Thread Diameter (X/Y): 8**"
ECHO: "**======> Thread Height (Z): 3.84**"
ECHO: "**======> Thread Pitch (P): 2.4**"
Compiling design (CSG Products generation)...
Geometries in cache: 36
Geometry cache size in bytes: 5820376
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized tree has 36 elements!
Compile and preview finished.
Total rendering time: 0:00:00.622


And "Render"
Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
ECHO: "--> Make "Bolt" Base"
ECHO: "----> Begin "Bolt" Base Creation"
ECHO: "**======> Base Diameter (D=X/Y): 31.983**"
ECHO: "**======> Base Height (Z): 5.7835**"
ECHO: "**======> Base Cutout Rotation Angle: 13**"
ECHO: "--> Make "Bolt" Grip"
ECHO: "----> Begin "Bolt" Grip Creation"
ECHO: "**======> Grip Width (X): 5.835**"
ECHO: "**======> Grip Length (Y): 59.935**"
ECHO: "**======> Grip Height (Z): 5.7835**"
ECHO: "--> Make "Bolt" Threads"
ECHO: "----> Begin "Bolt" Thread Creation"
ECHO: "**======> Thread Diameter (X/Y): 8**"
ECHO: "**======> Thread Height (Z): 47.5**"
ECHO: "**======> Thread Pitch (P): 2.4**"
ECHO: "--> Make "Bolt" Wire Eyelet"
ECHO: "----> Begin "Bolt" Eyelet Creation"
ECHO: "**======> Eyelet Width (X): 5.835**"
ECHO: "**======> Eyelet Height (Z): 9.88978**"
ECHO: "**======> Eyelet Radius (r): 15.9915**"
ECHO: "**======> Eyelet Extrusion Length: 27**"
ECHO: "**======> Eyelet Z-Rotation Offset Angle: 3**"
ECHO: "--> Make "Bolt" Wire Catch"
ECHO: "----> Begin "Bolt" Catch Creation"
ECHO: "**======> Catch Width (X): 5.835**"
ECHO: "**======> Catch Height (Z): 9.88978**"
ECHO: "**======> Catch Radius (r): 15.9915**"
ECHO: "**======> Catch Extrusion Length: 25.4**"
ECHO: "**======> Catch Z-Rotation Offset Angle: -20.83**"
ECHO: "--> Make "Screw" Base"
ECHO: "----> Begin "Screw" Base Creation"
ECHO: "**======> Base Diameter (D=X/Y): 14.9836**"
ECHO: "**======> Base Height (Z): 7.79505**"
ECHO: "--> Make "Screw" Grip"
ECHO: "----> Begin "Screw" Grip Creation"
ECHO: "**======> Grip Width (X): 5.835**"
ECHO: "**======> Grip Length (Y): 47.8**"
ECHO: "**======> Grip Height (Z): 6.62**"
ECHO: "--> Make "Screw" Threads"
ECHO: "----> Begin "Screw" Thread Creation"
ECHO: "**======> Thread Diameter (X/Y): 8**"
ECHO: "**======> Thread Height (Z): 6.62**"
ECHO: "**======> Thread Pitch (P): 2.4**"
ECHO: "--> Make "Screw" Wire Eyelet"
ECHO: "----> Begin "Screw" Eyelet Creation"
ECHO: "**======> Eyelet Width (X): 5.99605**"
ECHO: "**======> Eyelet Height (Z): 11.9921**"
ECHO: "**======> Eyelet Radius (r): 7.4918**"
ECHO: "**======> Eyelet Extrusion Length: 100**"
ECHO: "**======> Eyelet Z-Rotation Offset Angle: -98**"
ECHO: "--> Make "Cap" Threads"
ECHO: "----> Begin "Cap" Thread Creation"
ECHO: "**======> Thread Diameter (X/Y): 8**"
ECHO: "**======> Thread Height (Z): 3.84**"
ECHO: "**======> Thread Pitch (P): 2.4**"
Rendering Polygon Mesh using CGAL...
Geometries in cache: 79
Geometry cache size in bytes: 20250520
CGAL Polyhedrons in cache: 1
CGAL cache size in bytes: 92203888
Total rendering time: 0:01:34.841
   Top level object is a 3D object:
   Simple:        yes
   Vertices:    39150
   Halfedges:  214474
   Edges:      107237
   Halffacets: 136146
   Facets:      68073
   Volumes:         8
Rendering finished.

**Comment by jshessen** [comment]
@bassamanator -- This project is dependent upon the BOSL libraries.  Simple clone will not include the correct submodules referenced in the .scad file.

`use <external/BOSL/threading.scad>;`

 Please use the following to pull the submodule dependencies as well:
 
` git clone --recurse-submodules https://github.com/jshessen/SpringFactory.git`
