### ISSUE TITLE
Error when opening SpringDesigner.scad

### ISSUE THREAD

**Issue by en-vstanese** [jshessen/SpringFactory#2]
When opening the SpringDesigner.scad file I get the following error:
[ERROR: Parser error: syntax error in file external/ghoul/ghoul/strings.scad, line 199]
Execution aborted

And here is where I am being redirected for the issue:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/99820238/226943918-5aa437b6-eaa7-4252-b70b-825f46003113.png">

I am using OpenSCAD 2021.01 on MacOS Ventura 13.1.

**Comment by jshessen** [comment]
@en-vstanese,

I have updated the submodule references for this repo (both BOSL/GHOUL) which will correct this syntax issue.

As an aside, the SpringFactory is fairly mature.  However, the SpringDesigner was something I was working towards building out and have not revisited in a while.  The general concept was to build in the engineering/physics calculation to account for real-world load based upon the material which could then be used to more accurately define the SpringFactory values.

You will notice lots of "commented" calculation concepts etc., but at this point, the code is largely incomplete.

**Comment by en-vstanese** [comment]
I appreciate the clarification.

Indeed, updating the submodules fixed the issue.

Thank you for your quick response.

It can be closed!
