### ISSUE TITLE
Translate Issue

### ISSUE THREAD

**Issue by sc082997** [jshessen/SpringFactory#4]
When adjusting the bolt diameter the parts all translate their position. If adjusting the bolt diameter too low the parts (bolt, screw, and cap) will begin to intersect and the rendered geometry isn't usable. It appears that the bolt base and the screw are interlinked in a way that is causing an unintentional translate when lowering the diameter of the bolt.

**Comment by sc082997** [comment]
When the SYNC option is off the issue corrects itself.

**Comment by jshessen** [comment]
@sc082997 -- The previous parameter was almost exclusively focused on the diameter of the base, and the diameter of the bolt as it applied to the screw/cap placement.
`(bolt_base_diameter*.4)+(screw_base_diameter*.5)`


I have made a recent commit which should make this a bit more tolerant to smaller bolt diameters.
https://github.com/jshessen/SpringFactory/commit/4922d53523de887062757c9930095512a78a9c90
`(bolt_base_diameter*bolt_offset)+screw_grip_width`
